{% set name = "mc-goods" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mc_goods-{{ version }}.tar.gz
  sha256: 3544c5be5459475bb3b9397f057dfa7f709f76bb94b4131851e17266513903d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - intake
    - model_catalogs

test:
  imports:
    - mc_goods
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/axiom-data-science/mc-goods
  summary: model_catalogs catalogs for GOODS
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
